# Configuracoes do BD
spring.datasource.url=jdbc:postgresql://postgresql:5432/lance_bovino
spring.datasource.username=appspring
spring.datasource.password=12345

# Hibernate vai inserir comentarios no codigo SQL
spring.jpa.properties.hibernate.use_sql_comments=false
# Hibernate vai mostrar o SQL Formatado
spring.jpa.properties.hibernate.format_sql=false
# Gerar e fazer log de estatisticas
spring.jpa.properties.hibernate.generate_statistics=false

# Desabilita a injecao de propriedades de desenvolvimento
# pelo devtools
spring.devtools.add-properties=false