# Configuracoes do BD
spring.datasource.url=jdbc:postgresql://localhost:5432/lance_bovino
spring.datasource.username=appspring
spring.datasource.password=12345

# Hibernate vai inserir comentarios no codigo SQL
spring.jpa.properties.hibernate.use_sql_comments=true
# Hibernate vai mostrar o SQL Formatado
spring.jpa.properties.hibernate.format_sql=true
# Gerar e fazer log de estatisticas
# spring.jpa.properties.hibernate.generate_statistics=true
# Fazer logging de queries lentas
spring.jpa.properties.hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS=10

# Desabilitado pq meu controle de logging deve ser suficiente
# logging.level.web=debug