# Profile Spring ativo: dev ou prod
spring.profiles.active=dev  

spring.application.name=lance_bovino

# Definicao do caminho de contexto da aplicacao
#server.servlet.context-path=/meucaminhodecontexto

# Configuracoes de Locale
spring.web.locale=pt_BR
spring.web.locale-resolver=fixed

# Formato global para datas
spring.mvc.format.date=dd/MM/yyyy
spring.mvc.format.date-time=dd/MM/yyyy HH:mm

# Configurar o processamento em Batch quando possivel
spring.jpa.properties.hibernate.jdbc.batch_size=25
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Para evitar que o Thymeleaf acesse o BD usando JPA durante o processamento da view
spring.jpa.open-in-view=false

# Para evitar a validacao feita pela JPA
spring.jpa.properties.jakarta.persistence.validation.mode=none

# Habilitar filtro para métodos ocultos e garantir compatibilidade
spring.mvc.hiddenmethod.filter.enabled=true

# Para carregar as configuracoes dos formatadores
spring.config.import=optional:formatadores.properties

#HTTPS
server.port=8443
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=123456
server.ssl.key-alias=tomcat
